import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('paused-not-dropped.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const storage=new Map();
let consent=true;
const sandbox={console,confirm:()=>consent,localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
vm.createContext(sandbox);
vm.runInContext(script.slice(0,script.lastIndexOf('model = normalizeModel(model);')),sandbox);
const run=s=>vm.runInContext(s,sandbox);
assert.equal(run('normalizeModel({tasks:[]}).tasks.length'),0,'Explicitly empty task lists stay empty');
assert.equal(run('normalizeModel({tasks:[]}).wellbeing.episodes.length'),0,'Legacy data gains empty health collections');
run('model=normalizeModel({tasks:[{id:"test",title:"Existing task",state:"Done",goal:"body"}],today:[{text:"existing win"}],activity:[],futureField:"preserved",wellbeing:{episodes:[{id:"ep",title:"Test episode",updates:[{at:"2026-09-27T10:00:00Z",severity:4,note:"Test update"}]}],visits:[{id:"visit",providerId:"p",title:"Test visit"}],providers:[{id:"p",name:"Example clinic"}],checkins:[{id:"day",date:"2026-09-27",capacity:-60,progress:20}]}})');
assert.equal(run('model.tasks[0].state'),'Completed');
assert.equal(run('model.futureField'),'preserved');
const before=run('JSON.stringify(model)');
run('model=normalizeModel(JSON.parse(JSON.stringify(backupPayload())).model)');
assert.equal(run('JSON.stringify(model)'),before,'Backup / Sheet payload round trip retains task and health data');
assert.equal(run('backupPayload().version'),2);
consent=false;
assert.equal(run('prepareReplacement({tasks:[]})'),false,'Cancelled legacy replacement does not erase health records');
assert.equal(run('JSON.stringify(model)'),before);
consent=true;
assert.equal(run('prepareReplacement({tasks:[]})'),true);
assert.equal(run('JSON.parse(localStorage.getItem(storeKey+"-before-replace")).model.wellbeing.episodes[0].updates[0].note'),'Test update','Replacement saves full recovery copy');
assert.throws(()=>run('prepareReplacement({})'));
assert.equal(run('escapeHtml("<img onerror=alert(1)>")'),'&lt;img onerror=alert(1)&gt;');
run('model=normalizeModel({tasks:[{id:"a",goalIds:["body","career"],state:"Completed"},{id:"b",goalIds:["body"],state:"Started"},{id:"c",goalIds:["body"],state:"Made Progress"},{id:"d",goalIds:["body"],state:"Paused"},{id:"e",goalIds:["body"],state:"Dropped On Purpose"}],today:[{at:new Date(2026,8,27,12).toISOString(),goal:"body"},{at:new Date(2026,8,26,12).toISOString(),goal:"career"},{goal:"school"}]})');
assert.equal(run('goalProgress("body").percent'),25);
assert.equal(run('goalProgress("body").total'),4,'Released tasks excluded');
assert.equal(run('goalProgress("career").percent'),100,'Shared task counts within each linked goal');
assert.equal(run('goalProgress("body").counts.Paused'),1);
assert.equal(run('goalProgress("school").percent'),null,'No tasks is not zero percent');
assert.equal(run('todayEntries(new Date(2026,8,27,20)).length'),1,'Old and undated entries do not count as today');
assert.equal(run('todayEntries(new Date(2026,8,28,1)).length'),0,'Today rolls over without deleting history');
assert.ok(run('taskCard(model.tasks[0],false).includes("<select")'));
assert.ok(!run('taskCard(model.tasks[0],false).includes("state-button")'));
assert.ok(!run('taskCard(model.tasks[0],false).includes("</label>/div>")'));
run('renderAll=()=>{}; setTaskStatus("b","Completed")');
assert.equal(run('goalProgress("body").percent'),50,'Dropdown handler updates derived progress');
const logCount=run('model.today.length');
run('setTaskStatus("b","Completed");setTaskStatus("b","not-a-state")');
assert.equal(run('model.today.length'),logCount,'No-op or invalid statuses do not duplicate wins');
run('setTaskStatus("b","Started")');
assert.equal(run('goalProgress("body").percent'),25,'Reopened tasks adjust completion');
assert.equal(run('lifeCapacityLevels.length'),21);
assert.equal(run('lifeCapacityLevels.every(([value],index)=>value===-100+index*10)'),true);
assert.equal(run('capacityLabel(-100)'),'I went to the ER');
assert.equal(run('capacityLabel(100)'),'I did everything I wanted to do today');
assert.equal(run('capacityLabel(-65)'),'Earlier capacity rating','Legacy exact values remain supported');
console.log('PASS: migration, backup/sync round trip, recovery, escaping, per-goal status counts, shared and dropped tasks, date rollover, dropdown status updates and reopen.');
