import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('paused-not-dropped.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const storage=new Map();
let consent=true;
const sandbox={console,confirm:()=>consent,localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
vm.createContext(sandbox);
vm.runInContext(script.slice(0,script.lastIndexOf('model = normalizeModel(model);')),sandbox);
const run=s=>vm.runInContext(s,sandbox);
assert.equal(run('normalizeModel({tasks:[]}).tasks.length'),0,'Explicitly empty task lists stay empty');
assert.equal(run('normalizeModel({tasks:[]}).wellbeing.episodes.length'),0,'Legacy data gains empty health collections');
run('model=normalizeModel({tasks:[{id:"test",title:"Existing task",state:"Done",goal:"body"}],today:[{text:"existing win"}],activity:[],futureField:"preserved",wellbeing:{episodes:[{id:"ep",title:"Test episode",updates:[{at:"2026-09-27T10:00:00Z",severity:4,note:"Test update"}]}],visits:[{id:"visit",providerId:"p",title:"Test visit"}],providers:[{id:"p",name:"Example clinic"}],checkins:[{id:"day",date:"2026-09-27",capacity:-60,progress:20}]}})');
assert.equal(run('model.tasks[0].state'),'Completed');
assert.equal(run('model.futureField'),'preserved');
const before=run('JSON.stringify(model)');
run('model=normalizeModel(JSON.parse(JSON.stringify(backupPayload())).model)');
assert.equal(run('JSON.stringify(model)'),before,'Backup / Sheet payload round trip retains task and health data');
assert.equal(run('backupPayload().version'),2);
consent=false;
assert.equal(run('prepareReplacement({tasks:[]})'),false,'Cancelled legacy replacement does not erase health records');
assert.equal(run('JSON.stringify(model)'),before);
consent=true;
assert.equal(run('prepareReplacement({tasks:[]})'),true);
assert.equal(run('JSON.parse(localStorage.getItem(storeKey+"-before-replace")).model.wellbeing.episodes[0].updates[0].note'),'Test update','Replacement saves full recovery copy');
assert.throws(()=>run('prepareReplacement({})'));
assert.equal(run('escapeHtml("<img onerror=alert(1)>")'),'&lt;img onerror=alert(1)&gt;');
console.log('PASS: syntax, legacy migration, empty tasks, unknown fields, complete backup/sync round trip, replacement cancellation, recovery copy, invalid payload, HTML escaping.');

